using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityJS.Entities.Core;

namespace UnityJS.Editor
{
  public static class JsTypeStubGenerator
  {
    const string OutputPath = "Assets/StreamingAssets/unity.js/types/unity.d.ts";

    static readonly Dictionary<string, string> TypeMap = new()
    {
      { "System.Single", "number" },
      { "System.Int32", "number" },
      { "System.Boolean", "boolean" },
      { "Unity.Mathematics.float2", "float2" },
      { "Unity.Mathematics.float3", "float3" },
      { "Unity.Mathematics.float4", "float4" },
      { "Unity.Mathematics.quaternion", "quaternion" },
    };

    [InitializeOnLoadMethod]
    static void OnDomainReload()
    {
      var content = GenerateContent();
      if (File.Exists(OutputPath))
      {
        var existingHash = ComputeHash(File.ReadAllText(OutputPath));
        var newHash = ComputeHash(content);
        if (existingHash == newHash)
          return;
      }

      WriteOutput(content);
    }

    [MenuItem("Tools/JS/Generate Type Stubs")]
    public static void Generate()
    {
      var content = GenerateContent();
      WriteOutput(content);
    }

    static void WriteOutput(string content)
    {
      var dir = Path.GetDirectoryName(OutputPath);
      if (!Directory.Exists(dir))
        Directory.CreateDirectory(dir);

      File.WriteAllText(OutputPath, content);
      AssetDatabase.Refresh();
      Debug.Log($"[JsTypeStubs] Generated {OutputPath}");
    }

    static string ComputeHash(string text)
    {
      using var sha = SHA256.Create();
      var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(text));
      return Convert.ToBase64String(bytes);
    }

    internal static string GenerateContent()
    {
      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated>");
      sb.AppendLine("// DO NOT EDIT — this file is generated by JsTypeStubGenerator.cs");
      sb.AppendLine("// Regenerate via: Tools > JS > Generate Type Stubs");
      sb.AppendLine("// </auto-generated>");
      sb.AppendLine();

      GenerateEnums(sb);
      GenerateBridgedComponents(sb);

      return sb.ToString();
    }

    static readonly Dictionary<Type, string> s_enumNames = new();

    static void GenerateEnums(StringBuilder sb)
    {
      s_enumNames.Clear();

      var enums = new List<(string jsName, Type type)>();

      foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
      {
        Type[] types;
        try
        {
          types = asm.GetTypes();
        }
        catch
        {
          continue;
        }

        foreach (var t in types)
        {
          if (!t.IsEnum)
            continue;
          var attr = t.GetCustomAttribute<JsBridgeAttribute>();
          if (attr == null)
            continue;
          var jsName = !string.IsNullOrEmpty(attr.JsName)
            ? attr.JsName
            : ToScreamingSnakeCase(t.Name);
          enums.Add((jsName, t));
          s_enumNames[t] = t.Name;
        }
      }

      enums.Sort((a, b) => string.Compare(a.jsName, b.jsName, StringComparison.Ordinal));

      // Emit type aliases at top level (ambient)
      sb.AppendLine("// ── Enum Type Aliases ────────────────────────────────────");
      sb.AppendLine();
      foreach (var (jsName, type) in enums)
      {
        var enumValues = new List<string>();
        foreach (var name in Enum.GetNames(type))
          enumValues.Add(Convert.ToInt32(Enum.Parse(type, name)).ToString());
        var typeName = s_enumNames[type];
        sb.AppendLine($"type {typeName} = {string.Join(" | ", enumValues)};");
        sb.AppendLine();
      }

      // Store enums for later use in the module block
      s_enumList = enums;
    }

    static List<(string jsName, Type type)> s_enumList;

    static Dictionary<string, string> GetComponentDocs(Type componentType)
    {
      var typeName = $"UnityJS.Entities.Generated.Js{componentType.Name}Bridge";
      foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
      {
        var docsType = asm.GetType(typeName);
        if (docsType == null)
          continue;
        var field = docsType.GetField("Descriptions", BindingFlags.Public | BindingFlags.Static);
        return field?.GetValue(null) as Dictionary<string, string>;
      }

      return null;
    }

    static Dictionary<string, string> GetEnumDocs(Type enumType)
    {
      var typeName = $"UnityJS.Entities.Generated.Js{enumType.Name}Enum";
      foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
      {
        var docsType = asm.GetType(typeName);
        if (docsType == null)
          continue;
        var field = docsType.GetField("Descriptions", BindingFlags.Public | BindingFlags.Static);
        return field?.GetValue(null) as Dictionary<string, string>;
      }

      return null;
    }

    static void GenerateBridgedComponents(StringBuilder sb)
    {
      sb.AppendLine("// ── Component Interfaces (ambient) ──────────────────────");
      sb.AppendLine();

      var targets = new List<(string jsName, Type type, bool needAccessors, bool needSetters)>();

      foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
      {
        Type[] types;
        try
        {
          types = asm.GetTypes();
        }
        catch
        {
          continue;
        }

        foreach (var t in types)
        {
          if (!t.IsValueType || t.IsEnum)
            continue;
          var attr = t.GetCustomAttribute<JsBridgeAttribute>();
          if (attr == null)
            continue;
          var jsName = !string.IsNullOrEmpty(attr.JsName) ? attr.JsName : t.Name;
          targets.Add((jsName, t, attr.NeedAccessors, attr.NeedSetters));
        }

        // Assembly-level [JsBridge(typeof(T), ...)]
        foreach (var attr in asm.GetCustomAttributes<JsBridgeAttribute>())
        {
          if (attr.ComponentType == null)
            continue;
          var jsName = !string.IsNullOrEmpty(attr.JsName) ? attr.JsName : attr.ComponentType.Name;
          targets.Add((jsName, attr.ComponentType, attr.NeedAccessors, attr.NeedSetters));
        }
      }

      targets.Sort((a, b) => string.Compare(a.jsName, b.jsName, StringComparison.Ordinal));

      // Emit interfaces at top level (ambient)
      foreach (var (jsName, type, needAccessors, needSetters) in targets)
      {
        var className = type.Name;
        var docs = GetComponentDocs(type);

        if (docs != null && docs.TryGetValue("", out var classDesc))
          sb.AppendLine($"/** {classDesc} */");

        sb.AppendLine($"interface {className} {{");
        var fields = type.GetFields(BindingFlags.Public | BindingFlags.Instance);
        foreach (var field in fields)
        {
          var tsType = MapType(field.FieldType);
          if (tsType == null)
            continue;
          var fieldJsName = field.Name;
          if (docs != null && docs.TryGetValue(fieldJsName, out var fieldDesc))
            sb.AppendLine($"  /** {fieldDesc} */");
          sb.AppendLine($"  {fieldJsName}: {tsType};");
        }

        sb.AppendLine("}");
        sb.AppendLine();
      }

      // Emit module declaration for component accessors and enums
      sb.AppendLine("// ── Module: unity.js/components ─────────────────────────");
      sb.AppendLine();
      sb.AppendLine("declare module 'unity.js/components' {");

      // Enum constants
      if (s_enumList != null)
      {
        foreach (var (jsName, type) in s_enumList)
        {
          var enumDocs = GetEnumDocs(type);

          if (enumDocs != null && enumDocs.TryGetValue("", out var enumDesc))
            sb.AppendLine($"  /** {enumDesc} */");

          sb.AppendLine($"  export const {jsName}: {{");
          foreach (var name in Enum.GetNames(type))
          {
            var val = Convert.ToInt32(Enum.Parse(type, name));
            if (enumDocs != null && enumDocs.TryGetValue(name, out var memberDesc))
              sb.AppendLine($"    /** {memberDesc} */");
            sb.AppendLine($"    readonly {name}: {val};");
          }

          sb.AppendLine("  };");
          sb.AppendLine();
        }
      }

      // Component accessors
      foreach (var (jsName, type, needAccessors, needSetters) in targets)
      {
        var className = type.Name;
        var isComponent = typeof(Unity.Entities.IComponentData).IsAssignableFrom(type);
        if (!isComponent)
          continue;

        if (needSetters)
        {
          sb.AppendLine($"  export const {jsName}: ComponentAccessor<{className}>;");
        }
        else if (needAccessors)
        {
          sb.AppendLine($"  export const {jsName}: ReadonlyComponentAccessor<{className}>;");
        }
      }

      sb.AppendLine("}");
      sb.AppendLine();
    }

    static string MapType(Type type)
    {
      if (TypeMap.TryGetValue(type.FullName ?? "", out var tsType))
        return tsType;
      if (type.IsEnum && s_enumNames.TryGetValue(type, out _))
        return type.Name;
      return null;
    }

    internal static string ToSnakeCase(string input)
    {
      if (string.IsNullOrEmpty(input))
        return input;
      var sb = new StringBuilder();
      for (var i = 0; i < input.Length; i++)
      {
        var c = input[i];
        if (char.IsUpper(c))
        {
          if (i > 0 && !char.IsUpper(input[i - 1]))
            sb.Append('_');
          else if (
            i > 0
            && i < input.Length - 1
            && char.IsUpper(input[i - 1])
            && char.IsLower(input[i + 1])
          )
            sb.Append('_');
          sb.Append(char.ToLowerInvariant(c));
        }
        else
        {
          sb.Append(c);
        }
      }

      return sb.ToString();
    }

    static string ToScreamingSnakeCase(string input)
    {
      return ToSnakeCase(input).ToUpperInvariant();
    }
  }
}
