// Ambient type declarations for unity.js
// Geometry interfaces, utility types, and spatial shapes stay global (no import needed)

// ── Shared Geometry Types ────────────────────────────────

interface float2 {
  x: number;
  y: number;
  add(b: float2 | number): float2;
  sub(b: float2 | number): float2;
  mul(b: float2 | number): float2;
  div(b: float2 | number): float2;
  equals(b: float2 | number): boolean;
  readonly xx: float2;
  readonly xxx: float3;
  readonly xxxx: float4;
  readonly xxxy: float4;
  readonly xxy: float3;
  readonly xxyx: float4;
  readonly xxyy: float4;
  xy: float2;
  readonly xyx: float3;
  readonly xyxx: float4;
  readonly xyxy: float4;
  readonly xyy: float3;
  readonly xyyx: float4;
  readonly xyyy: float4;
  yx: float2;
  readonly yxx: float3;
  readonly yxxx: float4;
  readonly yxxy: float4;
  readonly yxy: float3;
  readonly yxyx: float4;
  readonly yxyy: float4;
  readonly yy: float2;
  readonly yyx: float3;
  readonly yyxx: float4;
  readonly yyxy: float4;
  readonly yyy: float3;
  readonly yyyx: float4;
  readonly yyyy: float4;
}

interface float3 {
  x: number;
  y: number;
  z: number;
  add(b: float3 | number): float3;
  sub(b: float3 | number): float3;
  mul(b: float3 | number): float3;
  div(b: float3 | number): float3;
  equals(b: float3 | number): boolean;
  readonly xx: float2;
  readonly xxx: float3;
  readonly xxxx: float4;
  readonly xxxy: float4;
  readonly xxxz: float4;
  readonly xxy: float3;
  readonly xxyx: float4;
  readonly xxyy: float4;
  readonly xxyz: float4;
  readonly xxz: float3;
  readonly xxzx: float4;
  readonly xxzy: float4;
  readonly xxzz: float4;
  xy: float2;
  readonly xyx: float3;
  readonly xyxx: float4;
  readonly xyxy: float4;
  readonly xyxz: float4;
  readonly xyy: float3;
  readonly xyyx: float4;
  readonly xyyy: float4;
  readonly xyyz: float4;
  xyz: float3;
  readonly xyzx: float4;
  readonly xyzy: float4;
  readonly xyzz: float4;
  xz: float2;
  readonly xzx: float3;
  readonly xzxx: float4;
  readonly xzxy: float4;
  readonly xzxz: float4;
  xzy: float3;
  readonly xzyx: float4;
  readonly xzyy: float4;
  readonly xzyz: float4;
  readonly xzz: float3;
  readonly xzzx: float4;
  readonly xzzy: float4;
  readonly xzzz: float4;
  yx: float2;
  readonly yxx: float3;
  readonly yxxx: float4;
  readonly yxxy: float4;
  readonly yxxz: float4;
  readonly yxy: float3;
  readonly yxyx: float4;
  readonly yxyy: float4;
  readonly yxyz: float4;
  yxz: float3;
  readonly yxzx: float4;
  readonly yxzy: float4;
  readonly yxzz: float4;
  readonly yy: float2;
  readonly yyx: float3;
  readonly yyxx: float4;
  readonly yyxy: float4;
  readonly yyxz: float4;
  readonly yyy: float3;
  readonly yyyx: float4;
  readonly yyyy: float4;
  readonly yyyz: float4;
  readonly yyz: float3;
  readonly yyzx: float4;
  readonly yyzy: float4;
  readonly yyzz: float4;
  yz: float2;
  yzx: float3;
  readonly yzxx: float4;
  readonly yzxy: float4;
  readonly yzxz: float4;
  readonly yzy: float3;
  readonly yzyx: float4;
  readonly yzyy: float4;
  readonly yzyz: float4;
  readonly yzz: float3;
  readonly yzzx: float4;
  readonly yzzy: float4;
  readonly yzzz: float4;
  zx: float2;
  readonly zxx: float3;
  readonly zxxx: float4;
  readonly zxxy: float4;
  readonly zxxz: float4;
  zxy: float3;
  readonly zxyx: float4;
  readonly zxyy: float4;
  readonly zxyz: float4;
  readonly zxz: float3;
  readonly zxzx: float4;
  readonly zxzy: float4;
  readonly zxzz: float4;
  zy: float2;
  zyx: float3;
  readonly zyxx: float4;
  readonly zyxy: float4;
  readonly zyxz: float4;
  readonly zyy: float3;
  readonly zyyx: float4;
  readonly zyyy: float4;
  readonly zyyz: float4;
  readonly zyz: float3;
  readonly zyzx: float4;
  readonly zyzy: float4;
  readonly zyzz: float4;
  readonly zz: float2;
  readonly zzx: float3;
  readonly zzxx: float4;
  readonly zzxy: float4;
  readonly zzxz: float4;
  readonly zzy: float3;
  readonly zzyx: float4;
  readonly zzyy: float4;
  readonly zzyz: float4;
  readonly zzz: float3;
  readonly zzzx: float4;
  readonly zzzy: float4;
  readonly zzzz: float4;
}

interface float4 {
  x: number;
  y: number;
  z: number;
  w: number;
  add(b: float4 | number): float4;
  sub(b: float4 | number): float4;
  mul(b: float4 | number): float4;
  div(b: float4 | number): float4;
  equals(b: float4 | number): boolean;
  readonly xx: float2;
  readonly xxx: float3;
  readonly xxxx: float4;
  readonly xxxy: float4;
  readonly xxxz: float4;
  readonly xxxw: float4;
  readonly xxy: float3;
  readonly xxyx: float4;
  readonly xxyy: float4;
  readonly xxyz: float4;
  readonly xxyw: float4;
  readonly xxz: float3;
  readonly xxzx: float4;
  readonly xxzy: float4;
  readonly xxzz: float4;
  readonly xxzw: float4;
  readonly xxw: float3;
  readonly xxwx: float4;
  readonly xxwy: float4;
  readonly xxwz: float4;
  readonly xxww: float4;
  xy: float2;
  readonly xyx: float3;
  readonly xyxx: float4;
  readonly xyxy: float4;
  readonly xyxz: float4;
  readonly xyxw: float4;
  readonly xyy: float3;
  readonly xyyx: float4;
  readonly xyyy: float4;
  readonly xyyz: float4;
  readonly xyyw: float4;
  xyz: float3;
  readonly xyzx: float4;
  readonly xyzy: float4;
  readonly xyzz: float4;
  xyzw: float4;
  xyw: float3;
  readonly xywx: float4;
  readonly xywy: float4;
  xywz: float4;
  readonly xyww: float4;
  xz: float2;
  readonly xzx: float3;
  readonly xzxx: float4;
  readonly xzxy: float4;
  readonly xzxz: float4;
  readonly xzxw: float4;
  xzy: float3;
  readonly xzyx: float4;
  readonly xzyy: float4;
  readonly xzyz: float4;
  xzyw: float4;
  readonly xzz: float3;
  readonly xzzx: float4;
  readonly xzzy: float4;
  readonly xzzz: float4;
  readonly xzzw: float4;
  xzw: float3;
  readonly xzwx: float4;
  xzwy: float4;
  readonly xzwz: float4;
  readonly xzww: float4;
  xw: float2;
  readonly xwx: float3;
  readonly xwxx: float4;
  readonly xwxy: float4;
  readonly xwxz: float4;
  readonly xwxw: float4;
  xwy: float3;
  readonly xwyx: float4;
  readonly xwyy: float4;
  xwyz: float4;
  readonly xwyw: float4;
  xwz: float3;
  readonly xwzx: float4;
  xwzy: float4;
  readonly xwzz: float4;
  readonly xwzw: float4;
  readonly xww: float3;
  readonly xwwx: float4;
  readonly xwwy: float4;
  readonly xwwz: float4;
  readonly xwww: float4;
  yx: float2;
  readonly yxx: float3;
  readonly yxxx: float4;
  readonly yxxy: float4;
  readonly yxxz: float4;
  readonly yxxw: float4;
  readonly yxy: float3;
  readonly yxyx: float4;
  readonly yxyy: float4;
  readonly yxyz: float4;
  readonly yxyw: float4;
  yxz: float3;
  readonly yxzx: float4;
  readonly yxzy: float4;
  readonly yxzz: float4;
  yxzw: float4;
  yxw: float3;
  readonly yxwx: float4;
  readonly yxwy: float4;
  yxwz: float4;
  readonly yxww: float4;
  readonly yy: float2;
  readonly yyx: float3;
  readonly yyxx: float4;
  readonly yyxy: float4;
  readonly yyxz: float4;
  readonly yyxw: float4;
  readonly yyy: float3;
  readonly yyyx: float4;
  readonly yyyy: float4;
  readonly yyyz: float4;
  readonly yyyw: float4;
  readonly yyz: float3;
  readonly yyzx: float4;
  readonly yyzy: float4;
  readonly yyzz: float4;
  readonly yyzw: float4;
  readonly yyw: float3;
  readonly yywx: float4;
  readonly yywy: float4;
  readonly yywz: float4;
  readonly yyww: float4;
  yz: float2;
  yzx: float3;
  readonly yzxx: float4;
  readonly yzxy: float4;
  readonly yzxz: float4;
  yzxw: float4;
  readonly yzy: float3;
  readonly yzyx: float4;
  readonly yzyy: float4;
  readonly yzyz: float4;
  readonly yzyw: float4;
  readonly yzz: float3;
  readonly yzzx: float4;
  readonly yzzy: float4;
  readonly yzzz: float4;
  readonly yzzw: float4;
  yzw: float3;
  yzwx: float4;
  readonly yzwy: float4;
  readonly yzwz: float4;
  readonly yzww: float4;
  yw: float2;
  ywx: float3;
  readonly ywxx: float4;
  readonly ywxy: float4;
  ywxz: float4;
  readonly ywxw: float4;
  readonly ywy: float3;
  readonly ywyx: float4;
  readonly ywyy: float4;
  readonly ywyz: float4;
  readonly ywyw: float4;
  ywz: float3;
  ywzx: float4;
  readonly ywzy: float4;
  readonly ywzz: float4;
  readonly ywzw: float4;
  readonly yww: float3;
  readonly ywwx: float4;
  readonly ywwy: float4;
  readonly ywwz: float4;
  readonly ywww: float4;
  zx: float2;
  readonly zxx: float3;
  readonly zxxx: float4;
  readonly zxxy: float4;
  readonly zxxz: float4;
  readonly zxxw: float4;
  zxy: float3;
  readonly zxyx: float4;
  readonly zxyy: float4;
  readonly zxyz: float4;
  zxyw: float4;
  readonly zxz: float3;
  readonly zxzx: float4;
  readonly zxzy: float4;
  readonly zxzz: float4;
  readonly zxzw: float4;
  zxw: float3;
  readonly zxwx: float4;
  zxwy: float4;
  readonly zxwz: float4;
  readonly zxww: float4;
  zy: float2;
  zyx: float3;
  readonly zyxx: float4;
  readonly zyxy: float4;
  readonly zyxz: float4;
  zyxw: float4;
  readonly zyy: float3;
  readonly zyyx: float4;
  readonly zyyy: float4;
  readonly zyyz: float4;
  readonly zyyw: float4;
  readonly zyz: float3;
  readonly zyzx: float4;
  readonly zyzy: float4;
  readonly zyzz: float4;
  readonly zyzw: float4;
  zyw: float3;
  zywx: float4;
  readonly zywy: float4;
  readonly zywz: float4;
  readonly zyww: float4;
  readonly zz: float2;
  readonly zzx: float3;
  readonly zzxx: float4;
  readonly zzxy: float4;
  readonly zzxz: float4;
  readonly zzxw: float4;
  readonly zzy: float3;
  readonly zzyx: float4;
  readonly zzyy: float4;
  readonly zzyz: float4;
  readonly zzyw: float4;
  readonly zzz: float3;
  readonly zzzx: float4;
  readonly zzzy: float4;
  readonly zzzz: float4;
  readonly zzzw: float4;
  readonly zzw: float3;
  readonly zzwx: float4;
  readonly zzwy: float4;
  readonly zzwz: float4;
  readonly zzww: float4;
  zw: float2;
  zwx: float3;
  readonly zwxx: float4;
  zwxy: float4;
  readonly zwxz: float4;
  readonly zwxw: float4;
  zwy: float3;
  zwyx: float4;
  readonly zwyy: float4;
  readonly zwyz: float4;
  readonly zwyw: float4;
  readonly zwz: float3;
  readonly zwzx: float4;
  readonly zwzy: float4;
  readonly zwzz: float4;
  readonly zwzw: float4;
  readonly zww: float3;
  readonly zwwx: float4;
  readonly zwwy: float4;
  readonly zwwz: float4;
  readonly zwww: float4;
  wx: float2;
  readonly wxx: float3;
  readonly wxxx: float4;
  readonly wxxy: float4;
  readonly wxxz: float4;
  readonly wxxw: float4;
  wxy: float3;
  readonly wxyx: float4;
  readonly wxyy: float4;
  wxyz: float4;
  readonly wxyw: float4;
  wxz: float3;
  readonly wxzx: float4;
  wxzy: float4;
  readonly wxzz: float4;
  readonly wxzw: float4;
  readonly wxw: float3;
  readonly wxwx: float4;
  readonly wxwy: float4;
  readonly wxwz: float4;
  readonly wxww: float4;
  wy: float2;
  wyx: float3;
  readonly wyxx: float4;
  readonly wyxy: float4;
  wyxz: float4;
  readonly wyxw: float4;
  readonly wyy: float3;
  readonly wyyx: float4;
  readonly wyyy: float4;
  readonly wyyz: float4;
  readonly wyyw: float4;
  wyz: float3;
  wyzx: float4;
  readonly wyzy: float4;
  readonly wyzz: float4;
  readonly wyzw: float4;
  readonly wyw: float3;
  readonly wywx: float4;
  readonly wywy: float4;
  readonly wywz: float4;
  readonly wyww: float4;
  wz: float2;
  wzx: float3;
  readonly wzxx: float4;
  wzxy: float4;
  readonly wzxz: float4;
  readonly wzxw: float4;
  wzy: float3;
  wzyx: float4;
  readonly wzyy: float4;
  readonly wzyz: float4;
  readonly wzyw: float4;
  readonly wzz: float3;
  readonly wzzx: float4;
  readonly wzzy: float4;
  readonly wzzz: float4;
  readonly wzzw: float4;
  readonly wzw: float3;
  readonly wzwx: float4;
  readonly wzwy: float4;
  readonly wzwz: float4;
  readonly wzww: float4;
  readonly ww: float2;
  readonly wwx: float3;
  readonly wwxx: float4;
  readonly wwxy: float4;
  readonly wwxz: float4;
  readonly wwxw: float4;
  readonly wwy: float3;
  readonly wwyx: float4;
  readonly wwyy: float4;
  readonly wwyz: float4;
  readonly wwyw: float4;
  readonly wwz: float3;
  readonly wwzx: float4;
  readonly wwzy: float4;
  readonly wwzz: float4;
  readonly wwzw: float4;
  readonly www: float3;
  readonly wwwx: float4;
  readonly wwwy: float4;
  readonly wwwz: float4;
  readonly wwww: float4;
}

interface quaternion {
  x: number;
  y: number;
  z: number;
  w: number;
}

// ── Utility Types ───────────────────────────────────────

type entity = number;

interface ComponentAccessor<T> {
  readonly __name: string;
  get(eid: entity): T | null;
  set(eid: entity, data: T): void;
}

interface ReadonlyComponentAccessor<T> {
  readonly __name: string;
  get(eid: entity): T | null;
}

interface ComponentClassAccessor<T> {
  readonly __jsComp: true;
  readonly __name: string;
  get(eid: entity): T | undefined;
  new(): T;
}

type AnyAccessor = ComponentAccessor<any> | ReadonlyComponentAccessor<any> | ComponentClassAccessor<any>;
type InferData<A> = A extends ComponentAccessor<infer T> ? T
  : A extends ReadonlyComponentAccessor<infer T> ? T
  : A extends ComponentClassAccessor<infer T> ? T : never;

interface QueryBuilder<T extends any[] = []> {
  withAll<A extends AnyAccessor[]>(...a: A): QueryBuilder<[...T, ...{ [K in keyof A]: InferData<A[K]> }]>;
  withNone(...tags: AnyAccessor[]): QueryBuilder<T>;
  build(): Query<T>;
}

interface Query<T extends any[]> {
  [Symbol.iterator](): Iterator<[entity, ...T]>;
}

/** State passed to onUpdate each tick. */
interface UpdateState { deltaTime: number; elapsedTime: number; }

// ── Tweak Commands ─────────────────────────────────────

declare function param<T extends string | number>(name: string, constraint: T[] | { min: T; max: T; step?: T }, defaultValue: T, description?: string): void;

// ── Spatial Shapes ──────────────────────────────────────

interface SpatialShapeObj {
  shape: number;
  radiusSq?: number;
  halfExtents?: float3;
  center?: float3;
  tag?: number;
}
